### ISSUE TITLE
NX generate CWD: library - PATH is doubled? 

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx-console#1969]
NX Console: 1.15.1

CWD:
` libs/portal/shared`
COMMAND: 
`nx g @nx/angular:library --name=wtf --projectNameAndRootFormat=as-provided --no-interactive --dry-run`

ERROR:
`The provided directory resolved relative to the current working directory "libs/portal/shared/libs/portal/shared/wtf/src/lib/wtf" does not exist under any project root. 
`

Why it there "libs/portal/shared/" two times in the path?

Similar when "derived" is used:

CWD:
` libs/portal/shared`
COMMAND: 
`nx g @nx/angular:library --name=wtf --projectNameAndRootFormat=derived --no-interactive --dry-run`

ERROR:
`The provided directory resolved relative to the current working directory "libs/portal/shared/libs/wtf/src/lib/wtf" does not exist under any project root.`

Now the path looks correct, but errors is thrown anyway.

Error is the same when "nx g @nx/angular:library --name=wtf --no-interactive --dry-run" is used (no projectNameAndRootFormat switch.

Only way how to generate library atm in our monorepo is to execute (cwd) in root and set it via directory + derived:
`nx g @nx/angular:library --name=wtf --buildable=true --directory=libs/shared --projectNameAndRootFormat=derived --no-interactive --dry-run`

RESULT

```
UPDATE nx.json
CREATE libs/shared/wtf/project.json
CREATE libs/shared/wtf/README.md
CREATE libs/shared/wtf/ng-package.json
CREATE libs/shared/wtf/package.json
CREATE libs/shared/wtf/tsconfig.json
CREATE libs/shared/wtf/tsconfig.lib.json
CREATE libs/shared/wtf/tsconfig.lib.prod.json
CREATE libs/shared/wtf/src/index.ts
CREATE libs/shared/wtf/src/lib/shared-wtf/shared-wtf.component.scss
CREATE libs/shared/wtf/src/lib/shared-wtf/shared-wtf.component.html
CREATE libs/shared/wtf/src/lib/shared-wtf/shared-wtf.component.ts
CREATE libs/shared/wtf/.eslintrc.json
```

NX,json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "affected": {
    "defaultBase": "master"
  },
  "cli": {
    "packageManager": "yarn"
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"],
      "cache": true
    },
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"],
      "cache": true
    },
    "build-storybook": {
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/.storybook/**/*",
        "{projectRoot}/.storybook/**/*",
        "{projectRoot}/tsconfig.storybook.json"
      ],
      "cache": true
    },
    "e2e": {
      "cache": true
    },
    "@nx/jest:jest": {
      "cache": true,
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    }
  },
  "generators": {
    "@nx/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "none",
      "e2eTestRunner": "cypress"
    },
    "@nx/angular:library": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "none",
      "buildable": true,
      "changeDetection": "OnPush",
      "displayBlock": true,
      "setParserOptionsProject": true,
      "skipModule": true,
      "skipTests": true,
      "strict": true
    },
    "@nx/angular:component": {
      "style": "scss",
      "changeDetection": "OnPush",
      "standalone": true,
      "displayBlock": true,
      "nameAndDirectoryFormat": "derived",
      "skipTests": true
    },
    "@nx/web:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nx/web:library": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest"
    }
  },
  "defaultProject": "portal",
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "sharedGlobals": [],
    "production": [
      "default",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/.storybook/**/*",
      "!{projectRoot}/**/*.stories.@(js|jsx|ts|tsx|mdx)",
      "!{projectRoot}/tsconfig.storybook.json",
      "!{projectRoot}/src/test-setup.[jt]s"
    ]
  }
}

Nx Version:
- Local: v17.1.3

**Comment by MaxKless** [comment]
that's really weird... I will have a look! 
Can you paste your 'nx report' results?

**Comment by montella1507** [comment]
```
Convert compiler options from json failed, No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["../../../../node_modules/@angular/localize/init/index.d.ts"]' and 'exclude' paths were '["node_modules","tmp"]'.

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/plugin         : 17.1.3
   @nx/storybook      : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 17.0.1
   @ngrx/component-store : 17.0.1
   @ngrx/effects         : 17.0.1
   @ngrx/router-store    : 17.0.1
   @ngrx/store           : 17.0.1
   @ngrx/store-devtools  : 17.0.1
   @storybook/angular    : 7.6.3
   ngxtension            : 1.4.0


```

**Comment by montella1507** [comment]
@MaxKless  i can give you remote control to my pc if you are willing to :-)

**Comment by MaxKless** [comment]
Hey! I'm working on some improvements in this area right now that should be merged to master this week. Let's revisit this issue once the changes are in.

**Comment by montella1507** [comment]
Ok :-)

**Comment by nhack** [comment]
Any updates on this?

I have the same issue.

>  Node   : 18.17.1
   OS     : darwin-x64
   npm    : 9.6.7
   
 >   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/angular        : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/storybook      : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   @nx/webpack        : 17.2.3
   typescript         : 5.2.2
   ---------------------------------------
   > Community plugins:
   @ngrx/effects            : 17.0.1
   @ngrx/router-store       : 17.0.1
   @ngrx/schematics         : 17.0.1
   @ngrx/store              : 17.0.1
   @ngrx/store-devtools     : 17.0.1
   @nxrocks/nx-spring-boot  : 9.2.1
   @storybook/angular       : 7.6.4
   angular-auth-oidc-client : 16.0.1

**Comment by MaxKless** [comment]
I just released a new version, can you try again?

**Comment by montella1507** [comment]
Webstorm, 1.16.1 plugin.
![image](https://github.com/nrwl/nx-console/assets/10418323/2d31a36e-8b12-464a-a6cc-960e644f9cd2)

"libs/shared/libs/shared/my/src/lib/my" 

still doubling path.

**Comment by montella1507** [comment]
@MaxKless  1.17.0 still not available
https://plugins.jetbrains.com/plugin/21060-nx-console

so i will wait.

**Comment by Nisalay** [comment]
> I just released a new version, can you try again?

plugin version: 1.17.0 (WebStorm)
Still have a problem 
![IMAGE 2024-01-18 10:37:20](https://github.com/nrwl/nx-console/assets/23431908/0154f5b4-e301-4c1f-bec9-b5a0ee3bd80d)

But if I run this command manually without the plugin I get the same problem:
<img width="1799" alt="Снимок экрана 2024-01-18 в 10 44 49" src="https://github.com/nrwl/nx-console/assets/23431908/5f12efd2-bf47-4d74-b551-0ffb06aa04f6">

**Comment by montella1507** [comment]
So it is not problem with nx-console, but with schematics ?

**Comment by pliersch** [comment]
same problem. creating angular apps works, but not libs. v1.18.0

**Comment by MaxKless** [comment]
So after digging in a bit I can confirm that this has nothing to do with Nx Console and is a problem with the `@nx/angular:lib` generator. I'm moving this issue over to the main nx repo and pinging someone.
