### ISSUE TITLE
VScode extention failing with pathing issue

### ISSUE THREAD

**Issue by rw-kmohan** [nrwl/nx-console#821]
![image](https://user-images.githubusercontent.com/19436246/63970681-5ef57700-ca6a-11e9-9461-658814de8de2.png)

I have set up a ng command and when I run it using cli , it works. However when I use the angular console vscode extention, it fails with the space issue in the pathing.

**Comment by wtang3** [comment]
Same here, also having this issue.

**Comment by JanneHarju** [comment]
Same here. How can I downgrade extension?

**Comment by Maus3rVonDutch** [comment]
Same here, noticed this when trying to run a custom schematic. Indeed it seems that the path used in the cmd execution is not properly escaped. This bug is introduced in version 8.1.0. FYI downgrading to version 8.0.10 resolved the issue for me. You can do that by clicking on the manage (gear) icon of the Angular Console extension in the extension list, in the context menu select "Install Another Version".

If I have some time later today maybe I can investigate this a bit further for any leads to where the bug occurs.

PS I hope any of the core contributers will investigate this any time soon, it's been reported 2 weeks ago, that seems ages to fix such (in my opinion) a small issue and this **is** a big show stopper, since you cannot use the tool properly this way.

**Comment by Maus3rVonDutch** [comment]
BTW I'm running on Windows 10, and using yarn, this is the exception I get

![image](https://user-images.githubusercontent.com/6672855/64677517-006fc600-d478-11e9-88a5-5dbb2417f5ae.png)

**Comment by mrmeku** [comment]
I'll get this fixed for the next release. Thanks so much for the bug report

**Comment by mrmeku** [comment]
This should be fixed with release 8.1.2. If there's a corner case I missed that you run into please do not hesitate to reopen the issue.

Thanks everyone for the bug report!

**Comment by JanneHarju** [comment]
8.1.2 still failing:

```
c:\WORK\Project\Project\ : The term 'c:\WORK\Project\Project\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ & {c:\WORK\Project\Project\ frontend\node_modules\.bin\ng.cmd generate @s ...
+    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\WORK\Project\Project\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

my local angular version:
Angular CLI: 7.3.3
Node: 10.15.0
OS: win32 x64
Angular: 7.2.6

and global cli version is 8.1.0

**Comment by JanneHarju** [comment]
How can I reopen this?

**Comment by nixallover** [comment]
@JanneHarju @urwrstkn8mare Thanks for letting us know that this is still an issue! The team will look into it.

**Comment by JanneHarju** [comment]
Your extension is evolving so fast and I forget to inform you that last week I managed to get it work. I see red pnly when input parameters are incorrect and that is fine and as it should be. I managed to generate several libraries and components. So currently I'm fine. However I can test it tomorrow at work if it still works.

**Comment by JanneHarju** [comment]
I did test it tonight. Version is still 8.1.2 and it is working. I have no idea what have changed in my machine. maybe some vs code update fix it.

**Comment by JanneHarju** [comment]
It is failing again. It worked in one project and broke in another. Now I get this kind of exception message:
```
c:\WORK\Folder\ProjectX\ : The term 'c:\WORK\Folder\ProjectX\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
```
Have you any suggestion where to look what might be causing this.

**Comment by JanneHarju** [comment]
OK. Sorry spam. I found problem. 
```
> Executing task: c:\WORK\ProjectY\node_modules\.bin\ng.cmd generate @schematics/angular:component asdsad --module=modules\test\test.module.ts --dry-run --no-interactive <
> Executing task: c:\WORK\Folder\Project frontend\node_modules\.bin\ng.cmd generate @schematics/angular:component dsasd --module=modules\test\test.module.ts --dry-run --no-interactive <
```
Problem is related to my folder name your ng command doesn't work when my project is in folder structure which have space in some folder name.
First row works and second fails because there is "Project frontend" has space in it.

**Comment by urwrstkn8mare** [comment]
Yeah that's what I was talking about in #851. I also suggested a fix. The weird thing is I only have this problem in Ng serve not generate. I worked around the problem for now by running Ng serve from the command palette and not the UI.

**Comment by JanneHarju** [comment]
What is status of this? Do you need something else or will two quotes fix this issue?

**Comment by urwrstkn8mare** [comment]
I'm not sure if this has been fixed yet but I am fairly certain two quotes around paths in the line to be executed will fix the issue. For now, I am not too worried as I have found ways around it.

**Comment by JanneHarju** [comment]
@nixallover What is status of this issue?

**Comment by mediantiba** [comment]
Same thing on my machine, my user's folder contain a space and therefore I'm unable to use the angular console. The parser is inserting an escape backslash before the space in my folder's name, thus seeing it at two separate folders.

Path to project
`C:\Users\Name Surname\Source\Repos\my-awesome-project`

When trying to use the Angular Console to generate a component, it parses the path as follows
`C:\Users\Name\ Surname\Source\Repos\my-awesome-project`

And since such a path doesn't exist, it's failing.

**Comment by mrmeku** [comment]
Sorry this took me so long to figure out. I had no idea how to escape spaces in powershell until now. You have to use backticks instead of the unix style / character.

**Comment by Cammisuli** [comment]
Fixed with #890
