### ISSUE TITLE
"Unrecognized token in source text" when generating application

### ISSUE THREAD

**Issue by jorwoody** [nrwl/nx-console#860]
Hi there,

I have been following the tutorial to create an Nx workspace for my new group of applications. After creating the empty Angular workspace, I installed the Angular Console extension in VS Code. I'm trying to use the Generate feature to create the initial application, but running into an error in the generated command...

![image](https://user-images.githubusercontent.com/3836666/67222965-0603e880-f3f4-11e9-9198-f0ce635ef5fb.png)

I notice that it seems to be using an absolute path to ng.cmd, instead of just using "ng" as I've seen it should be doing in the tutorial video. In another console window I can run "ng" commands just fine, as it is installed globally and there is a reference to "C:\Users\jordanw\AppData\Roaming\npm" in my PATH.

I'm developing on Windows 7. My globally installed Angular CLI version is "8.3.12", and I upgraded the devDependencies in my workspace's package.json to match that.

Any ideas what I could do to resolve this? Let me know if I can provide any more information.

Thanks in advance,
Jordan

**Comment by JacksonFaller** [comment]
Hello. I'm facing the same issue. Win 7, Angular CLI 8.3.14. I also have a reference to npm, and ng command works just fine. @jorwoody any progress so far?

**Comment by jorwoody** [comment]
> Hello. I'm facing the same issue. Win 7, Angular CLI 8.3.14. I also have a reference to npm, and ng command works just fine. @jorwoody any progress so far?

Unfortunately, no. I've just been using the CLI. You can view the dry-run command for reference of how to use the flags, but still need to run on your own. Would love to fix it so I could use Console to it's full effectiveness. :(

**Comment by JacksonFaller** [comment]
@jorwoody I'm currently using Angular Schematics to generate components and stuff, maybe you should give it a shot.

**Comment by jaysoo** [comment]
@JacksonFaller @jorwoody We fixed a few Windows issues with the latest 9.0.1 vscode extension release. Do you still experience this problem?

**Comment by JacksonFaller** [comment]
@jaysoo Hello. Just tried and the issue is still present for version 9.0.1

**Comment by Feffy** [comment]
@jaysoo Still facing this issue with version 10.0.0 on Windows 7 and Angular CLI 8.3.3

**Comment by Cammisuli** [comment]
I'm going to have to confirm that this is fixed. I'll have to check on a Windows VM.

**Comment by Cammisuli** [comment]
I tried this out on Windows, and it looks like it's not happening (especially because we don't have this old UI anymore)

**Comment by VasilisG** [comment]
In case you're still facing the specific issue on a Windows 7 system, you can try enclosing `@nrwl/angular:component` in double quotes:
```
npx nx generate "@nrwl/angular:component" shop --project=store
```
