### ISSUE TITLE
Move errors

### ISSUE THREAD

**Issue by kdawg1406** [nrwl/nx-console#961]
[Lab 9 Nx Workshop - Building a Board Game Store](https://github.com/nrwl/nx-workshop/issues/1)

Got an error in Lab 9 when attempting to move the library. Is this a bug or a known issue?

It worked when Jason did it in the Pluralsight Course video in Part 4.

nx generate @nrwl/workspace:move --projectName=api-util-interface util-interface
**ENOTEMPTY**: **directory not empty**, rmdir 'C:\Code\vsCode\nx-workshop\bg-hoard\libs\api\util-interface\src'

This error messed up my project, it deleted the files but didn't create the new ones that --dry-run indicated it would. I'm so glad I checked in before attempting this.

nx --version
9.5.1

ng --version
Angular: 9.1.11

Thank you!

Karl

**Comment by kdawg1406** [comment]
@jeffbcross I've seen a number of Move issues report in the Nx repro. Did someone also look at this one?  Reported a month ago with being addressed.  

I bring this up since we are looking at adopting Nx and are seeing a good number of issues with Nx.  Thank you for understanding.  I love Nx and want to stake our future on it.

Thank you,

Karl

**Comment by jeffbcross** [comment]
@FrozenPandaz or @vsavkin is this a known issue with `nx move` on windows?

**Comment by isaacplmann** [comment]
This issue belongs on the nrwl/nx repo and is likely fixed by now.

**Comment by paulyipkh** [comment]
![image](https://user-images.githubusercontent.com/12554293/96365401-efad7b80-1172-11eb-9124-b448ee19140d.png)

I still encounter this problem in windows.
